# Generated by Django 4.2.6 on 2024-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
