# Generated by Django 4.2.6 on 2024-02-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='latitude',
            new_name='lattitude',
        ),
    ]
