# Generated by Django 4.2.6 on 2024-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_rename_organization_type_user_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
